version: '3'
services:
  api-gateway:
    build: ./api-gateway
    restart: on-failure
    hostname: api-gateway
    env_file:
      - .env
    ports:
      - "8000:8080"
    networks:
      - backend
    depends_on:
      - user-service
      - task-service
      - notification-service
      - rmq-infrastructure

  task-service:
    build: ./task-microservice
    restart: on-failure
    hostname: task-microservice
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - db
      - rmq-infrastructure

  notification-service:
    build: ./notification-microservice
    restart: on-failure
    hostname: notification-microservice
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - db
      - rmq-infrastructure

  user-service:
    build: ./user-microservice
    restart: on-failure
    hostname: user-microservice
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - db
      - rmq-infrastructure

  db:
    image: 'postgres:14.1-alpine'
    restart: on-failure
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    expose:
      - 5432
    networks:
      - backend

  rmq-infrastructure:
    image: rabbitmq
    ports:
      - "5672:5672"
    networks:
      - backend

networks:
  backend:
    driver: bridge